/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adressverwaltung.forms;

import adressverwaltung.services.FileSystemService;
import adressverwaltung.errors.CanNotConnectToDatabaseError;
import adressverwaltung.main;
import adressverwaltung.enums.SystemPropertyEnum;
import adressverwaltung.errors.DatabaseSelfHealingError;
import adressverwaltung.utils.CustomFocusTraversalPolicy;
import adressverwaltung.utils.DotEnv;
import adressverwaltung.utils.InOut;
import adressverwaltung.utils.MySQLConnection;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Christof Weickarhdt
 */
public class ConnectionForm extends javax.swing.JFrame {

    boolean tested = false;
    String home = SystemPropertyEnum.USER_HOME.get();

    /**
     * Creates new form ConnectionForm
     */
    public ConnectionForm() {
        this.setTitle("Connection");
        initComponents();
        ArrayList<Component> list = new ArrayList<>();
        list.add(jRadioButton1);
        list.add(jRadioButton2);
        list.add(jTextField1);
        list.add(jTextField2);
        list.add(jTextField3);
        list.add(jTextField4);
        list.add(jSpinner1);
        list.add(jButton1);
        list.add(jButton2);
        setFocusTraversalPolicy(new CustomFocusTraversalPolicy(list));

        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jSpinner1.setEnabled(false);
        jLabel7.setText("");
        setResizable(false);

        if (!new File(home).canRead()) {
            home = System.getProperty("user.dir");
        }

        HashMap<String, String> dotEnv = DotEnv.getDotEnv();

        if (!dotEnv.isEmpty() && dotEnv.containsKey("DATABASE_USE")) {
            jTextField1.setText(dotEnv.containsKey("DATABASE_HOST") ? dotEnv.get("DATABASE_HOST") : "localhost");
            jTextField2.setText(dotEnv.containsKey("DATABASE_NAME") ? dotEnv.get("DATABASE_NAME") : "adv");
            jTextField3.setText(dotEnv.containsKey("DATABASE_USER") ? dotEnv.get("DATABASE_USER") : "root");
            jTextField4.setText(dotEnv.containsKey("DATABASE_PASSWORD") ? dotEnv.get("DATABASE_PASSWORD") : "");
            jSpinner1.setValue(new Integer(dotEnv.containsKey("DATABASE_PORT") ? dotEnv.get("DATABASE_PORT") : "3306"));
            if (dotEnv.get("DATABASE_USE").equals("true")) {
                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jTextField3.setEnabled(true);
                jTextField4.setEnabled(true);
                jSpinner1.setEnabled(true);

                System.out.println("Connecting database...");

                try {
                    new MySQLConnection(jTextField1.getText(), jTextField4.getText(), jTextField2.getText(), jSpinner1.getValue() + "", jTextField3.getText(), false, "mysql").verify();
                } catch (CanNotConnectToDatabaseError ex) {
                    jButton2.setEnabled(false);
                }
                jRadioButton2.setSelected(true);
                jRadioButton1.setSelected(false);
            } else {
                jButton1.setText("Clear fsdb");
            }
        } else {
            jButton1.setText("Clear fsdb");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Connection Information");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("File System");
        jRadioButton1.setName("fs"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("MySQL Database");
        jRadioButton2.setName("mysql"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("localhost");
        jTextField1.setName("Host"); // NOI18N

        jTextField2.setText("adressverwaltung");
        jTextField2.setName("Table"); // NOI18N

        jTextField3.setText("root");
        jTextField3.setName("User"); // NOI18N

        jTextField4.setName("Password"); // NOI18N

        jLabel2.setText("DB Name");

        jLabel3.setText("DB Host");

        jLabel4.setText("DB User");

        jLabel5.setText("DB Password");

        jLabel6.setText("DB Port");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3306, null, null, 1));
        jSpinner1.setName("Port"); // NOI18N
        jSpinner1.setValue(3306);

        jLabel7.setText("jLabel7");
        jLabel7.setName("status"); // NOI18N

        jButton1.setText("Test Connection");
        jButton1.setName("clearOrtest"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lets Go");
        jButton2.setName("letsgo"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jSpinner1))))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jSpinner1.setEnabled(false);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton1.setText("Clear fsdb");
        jLabel7.setText("Files are stored in your root .fsdb folder");
    }// GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        jSpinner1.setEnabled(true);
        tested = false;
        jButton1.setText("Test Connection");
        jLabel7.setText(tested ? "Database Connected" : "Let's configure your db connection");
    }// GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        try {
            HashMap<String, String> connectionMap = new HashMap<>();
            if (jRadioButton1.isSelected()) {
                connectionMap.put("DATABASE_USE", "false");
            }
            if (jRadioButton2.isSelected()) {
                connectionMap.put("DATABASE_USE", "true");
                connectionMap.put("DATABASE_HOST", jTextField1.getText());
                connectionMap.put("DATABASE_NAME", jTextField2.getText());
                connectionMap.put("DATABASE_USER", jTextField3.getText());
                connectionMap.put("DATABASE_PASSWORD", jTextField4.getText());
                connectionMap.put("DATABASE_PORT", jSpinner1.getValue() + "");
            }
            DotEnv.setDotEnv(connectionMap);
            main.setupConnection(null);
            main.viewAdressForm();
        } catch (IOException | SQLException | CanNotConnectToDatabaseError ex) {
            Logger.getLogger(ConnectionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            HashMap<String, String> fakeKeys = new HashMap<>();
            fakeKeys.put("DATABASE_USE", "false");
            try {
                InOut io = new InOut(fakeKeys);
                ((FileSystemService) io.connection).clean();
            } catch (SQLException | CanNotConnectToDatabaseError | DatabaseSelfHealingError ex) {}
        } else {
            try {
                new MySQLConnection(jTextField1.getText(), jTextField4.getText(), jTextField2.getText(), jSpinner1.getValue() + "", jTextField3.getText(), false, "mysql").verify();
                System.out.println("Database connected!");
                jLabel7.setText("Database Connected");
                tested = true;
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);

            } catch (CanNotConnectToDatabaseError ex) {
                jLabel7.setText("<html><font color='red'>Testing connection to database failed</font></html>");
                tested = false;
                jButton1.setEnabled(true);
                jButton2.setEnabled(false);

            }
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
